# Resource object code (Python 3)
# Created by: object code
# Created by: The Resource Compiler for Qt version 6.6.2
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore

qt_resource_data = b"\
\x00\x00+R\
A\
4\x0aable\x0aabout\x0aabo\
ve\x0aabsence\x0aabsol\
utely\x0aabstract\x0aa\
ccess\x0aaccording\x0a\
accumulated\x0aachi\
eve\x0aachieving\x0aac\
tivity\x0aacts\x0aactu\
al\x0aactually\x0aadd\x0a\
added\x0aadding\x0aadd\
ition\x0aadditional\
ly\x0aadditions\x0aadd\
resses\x0aadjust\x0aad\
justments\x0aadvanc\
ed\x0aadvice\x0aafter\x0a\
afterwards\x0aagain\
\x0aagenda\x0aaim\x0aalgo\
rithm\x0aall\x0aalloca\
ted\x0aallow\x0aallowe\
d\x0aallowing\x0aallow\
s\x0aalong\x0aalpha\x0aal\
ready\x0aalso\x0aalter\
native\x0aalternati\
vely\x0aalthough\x0aAm\
erican\x0aan\x0aand\x0aan\
nounced\x0aannoy\x0aan\
other\x0aanswer\x0aans\
wers\x0aany\x0aanythin\
g\x0aanyway\x0aapart\x0aA\
PI\x0aappear\x0aappear\
s\x0aappendices\x0aapp\
endix\x0aappends\x0aap\
plication\x0aapplic\
ations\x0aapply\x0aapp\
roach\x0aapproaches\
\x0aappropriate\x0aAra\
bic\x0aarbitrary\x0aar\
e\x0aareas\x0aARGB\x0aarg\
ument\x0aarguments\x0a\
around\x0aarrangeme\
nts\x0aarrive\x0aarriv\
ed\x0aArthur\x0aarticl\
e\x0aarticles\x0aas\x0aas\
ked\x0aaspects\x0aassu\
me\x0aat\x0aattachment\
\x0aattempt\x0aattempt\
ing\x0aattend\x0aatten\
dees\x0aattributes\x0a\
authors\x0aavailabi\
lity\x0aavailable\x0aa\
void\x0aaway\x0aback\x0ab\
ackground\x0abackgr\
ounds\x0abandwidth\x0a\
bandwidths\x0aBarce\
lona\x0abase\x0abased\x0a\
basic\x0abasically\x0a\
basics\x0abe\x0abecaus\
e\x0abeen\x0abefore\x0abe\
have\x0abehavior\x0abe\
hind\x0abeing\x0abelow\
\x0abenefits\x0aBerkel\
ey\x0abetween\x0abit\x0ab\
its\x0abitwise\x0ablac\
k\x0ablended\x0ablendi\
ng\x0ablends\x0ablock\x0a\
blue\x0aBMP\x0abody\x0abo\
ld\x0abooking\x0abool\x0a\
Boston\x0aboth\x0abott\
om\x0abox\x0aboxes\x0abra\
ces\x0abreak\x0abreaks\
\x0abroad\x0abrowsers\x0a\
buffer\x0abuffers\x0ab\
uild\x0abuilds\x0abuil\
t\x0abundled\x0aburden\
s\x0abusy\x0abut\x0aby\x0aby\
pass\x0abypassing\x0ab\
ytes\x0acalendar\x0aca\
ll\x0acalled\x0acallin\
g\x0acalls\x0aCambridg\
e\x0acan\x0acanonical\x0a\
canonicalised\x0aca\
p\x0acapabilities\x0ac\
apacity\x0acaption\x0a\
card\x0acare\x0acase\x0ac\
ast\x0acatch\x0acausin\
g\x0acentre\x0acertain\
\x0achallenges\x0achan\
ce\x0achange\x0achange\
s\x0achanging\x0achann\
el\x0achannels\x0achap\
ter\x0achar\x0achart\x0ac\
harts\x0acheck\x0achec\
ks\x0aChicago\x0achose\
n\x0achunk\x0acircle\x0ac\
itation\x0acity\x0acla\
im\x0aclass\x0aclasses\
\x0aclause\x0aclauses\x0a\
clear\x0aclearing\x0ac\
lient\x0aclients\x0acl\
ose\x0aclosed\x0acode\x0a\
colon\x0acolor\x0acolo\
rize\x0acolorizer\x0ac\
olors\x0acolour\x0acol\
umn\x0acolumns\x0acomb\
ine\x0acombined\x0acom\
bines\x0acombining\x0a\
comes\x0acommand\x0aco\
mmands\x0acomment\x0ac\
ommon\x0acommunicat\
e\x0acommunity\x0acomp\
iled\x0acomplement\x0a\
complete\x0acomplet\
ely\x0acompleteness\
\x0acompletes\x0acompl\
etion\x0acomplex\x0aco\
mpliant\x0acomponen\
t\x0acomponents\x0acom\
positing\x0acomposi\
tion\x0acompression\
\x0acomputation\x0acom\
puter\x0aconcepts\x0ac\
onclusion\x0aconcur\
rent\x0aconfigurabl\
e\x0acongested\x0acong\
estion\x0aconnect\x0ac\
onnected\x0aconnect\
ion\x0aconnections\x0a\
cons\x0aconsider\x0aco\
nsisting\x0aconsist\
s\x0aconstruct\x0acons\
tructed\x0aconstruc\
ting\x0aconstructor\
\x0aconstructs\x0acons\
ume\x0acontact\x0acont\
ain\x0acontaining\x0ac\
ontains\x0acontents\
\x0acontents\x0acontin\
ue\x0acontinued\x0acon\
tributors\x0acontro\
l\x0acontrolled\x0acon\
troller\x0acontroll\
er\x0acontrolling\x0ac\
ontrols\x0acontrols\
\x0aconventions\x0acoo\
k\x0acooperation\x0aco\
py\x0acopyright\x0acor\
e\x0acores\x0acorollar\
y\x0acorrect\x0acorrec\
tly\x0acorrespondin\
g\x0acould\x0acouple\x0ac\
oworkers\x0aCPU\x0acre\
ate\x0acreates\x0acrea\
ting\x0acrucial\x0acul\
tures\x0acurrent\x0acu\
rrently\x0acustom\x0ac\
ustomized\x0acut\x0ada\
ta\x0adatabase\x0adata\
sets\x0adatum\x0aday\x0ad\
ays\x0adeal\x0adealing\
\x0adecide\x0adecouple\
\x0adecoupled\x0adeepl\
y\x0adef\x0adefault\x0ade\
fine\x0adefines\x0adef\
inition\x0adefiniti\
ons\x0adelegate\x0adel\
ete\x0ademo\x0ademonst\
rate\x0ademonstrati\
ons\x0adeployed\x0ades\
cribe\x0adescribes\x0a\
design\x0adesktop\x0ad\
esktops\x0adestinat\
ion\x0adestinations\
\x0adestructor\x0adeta\
ils\x0adetect\x0adeter\
mine\x0adetermines\x0a\
developer\x0adevelo\
pers\x0adevelopment\
\x0adevelopments\x0ade\
vice\x0adevices\x0adia\
gram\x0adialogs\x0adic\
tionary\x0adid\x0adiff\
erence\x0adifferenc\
es\x0adifferent\x0adif\
fers\x0adigital\x0adir\
ect\x0adirect\x0adirec\
tions\x0adirectly\x0ad\
irectory\x0adiscuss\
\x0adisplay\x0adisplay\
ing\x0adisplays\x0adis\
tribute\x0adistribu\
tion\x0adisturbing\x0a\
divide\x0ado\x0adocume\
ntation\x0adocument\
s\x0adoes\x0adone\x0adown\
\x0adownLimit\x0adownl\
oad\x0adownloaded\x0ad\
ownloading\x0adraw\x0a\
drawing\x0adrawn\x0adr\
op\x0aDuff\x0aduring\x0aD\
VD\x0adynamic\x0adynam\
ically\x0adynamics\x0a\
each\x0aearlier\x0aeas\
ily\x0aediting\x0aedit\
ors\x0aeducation\x0aef\
fect\x0aeffectively\
\x0aeffects\x0aeither\x0a\
ellipse\x0aellipses\
\x0aelliptical\x0aelse\
\x0aemail\x0aembedded\x0a\
emit\x0aemits\x0aempty\
\x0aenable\x0aenables\x0a\
encapsulates\x0aenc\
lose\x0aend\x0aendnote\
\x0aendnotes\x0aengine\
er\x0aengineering\x0aE\
nglish\x0aenjoys\x0aen\
ough\x0aensure\x0aensu\
res\x0aentails\x0aente\
r\x0aentire\x0aentitle\
d\x0aentries\x0aentry\x0a\
environment\x0aeras\
es\x0aerror\x0aerrors\x0a\
especially\x0aestab\
lished\x0aetc.\x0aEuro\
pe\x0aeven\x0aevenly\x0ae\
vent\x0aevents\x0aeven\
tually\x0aevery\x0aeve\
ryone\x0aexample\x0aex\
amples\x0aexcept\x0aex\
ception\x0aexcessiv\
e\x0aexclusive\x0aexis\
ting\x0aexists\x0aexpa\
nd\x0aexpected\x0aexpe\
nse\x0aexport\x0aexpos\
es\x0aextend\x0aextend\
ed\x0aextending\x0aext\
ensible\x0aextensio\
n\x0aexternal\x0aextra\
\x0aextract\x0afaces\x0af\
acilities\x0afactor\
y\x0afade\x0afailure\x0af\
airness\x0afalls\x0afa\
lse\x0afamily\x0afashi\
on\x0afast\x0afaster\x0af\
eatures\x0aFebruary\
\x0afeedback\x0afeel\x0af\
etch\x0afetching\x0afe\
w\x0afields\x0afigure\x0a\
figures\x0afile\x0afil\
e name\x0afiles\x0afil\
led\x0afiller\x0afinal\
\x0afinally\x0afind\x0afi\
ne\x0afinish\x0afinish\
ed\x0afirst\x0aflow\x0afl\
y\x0afocus\x0afollowed\
\x0afollowing\x0afont\x0a\
foot\x0afootnote\x0afo\
otnotes\x0afor\x0aform\
\x0aformat\x0aformats\x0a\
forms\x0aformula\x0afo\
rmulas\x0aforum\x0afou\
nd\x0aframework\x0aFra\
nce\x0afrom\x0afront\x0af\
ull\x0afully\x0afuncti\
on\x0afunctionality\
\x0afunctions\x0afutur\
e\x0again\x0agames\x0agap\
\x0ageneral\x0ageneric\
\x0aGermany\x0aget\x0agil\
l\x0agive\x0agiven\x0agiv\
es\x0agiving\x0aglobal\
\x0ago\x0agoes\x0agot\x0agra\
dient\x0agraph\x0agrap\
hical\x0agraphics\x0ag\
ray\x0agreat\x0agreatl\
y\x0agreen\x0agrey\x0agro\
up\x0agrowing\x0agui\x0aG\
UI\x0ahack\x0ahad\x0ahalf\
\x0aHamburg\x0ahand\x0aha\
nding\x0ahandle\x0ahan\
dler\x0ahandlers\x0aha\
ndles\x0ahandling\x0ah\
appens\x0ahardware\x0a\
harmonica\x0ahas\x0aha\
ve\x0ahaving\x0ahe\x0ahea\
d\x0aheader\x0aheaders\
\x0ahear\x0aheight\x0ahel\
p\x0ahelper\x0ahere\x0ahi\
gh\x0ahighlight\x0ahig\
hly\x0ahints\x0ahis\x0aho\
ld\x0aholder\x0aholdin\
g\x0ahole\x0ahome\x0ahori\
zontal\x0ahost\x0ahost\
ing\x0ahours\x0aHousto\
n\x0ahow\x0ahowever\x0ahu\
ge\x0ahyphen\x0aID\x0aide\
a\x0aideally\x0aif\x0aIll\
inois\x0aillustrate\
\x0aillustrated\x0aill\
ustrates\x0aimage\x0ai\
mages\x0aimpact\x0aimp\
lement\x0aimplement\
ation\x0aimplementa\
tions\x0aimplemente\
d\x0aimplementing\x0ai\
mplements\x0aimport\
\x0aimportant\x0aimpro\
vements\x0ain\x0ainclu\
de\x0aincluded\x0aincl\
udes\x0aincluding\x0ai\
nclusion\x0aincomin\
g\x0ainconvenient\x0ai\
ndent\x0aindex\x0aindi\
cate\x0ainexpensive\
ly\x0ainfluence\x0ainf\
o\x0ainformation\x0ain\
genious\x0ainherits\
\x0ainitial\x0ainitial\
ly\x0ainner\x0ainput\x0ai\
nspired\x0ainstall\x0a\
installs\x0ainstanc\
e\x0ainstead\x0ainstru\
cts\x0ainteger\x0ainte\
gers\x0aintegration\
\x0aintended\x0aintens\
ive\x0ainterest\x0aint\
erests\x0ainterface\
\x0ainterfaces\x0ainte\
rfere\x0ainternal\x0ai\
nterval\x0ainto\x0aint\
riguing\x0aintro\x0ain\
troduce\x0aintroduc\
ed\x0ainvalid\x0ainven\
ted\x0ainverse\x0ainvo\
cation\x0ainvolved\x0a\
Irish\x0airregular\x0a\
is\x0aISO\x0aISPs\x0aissu\
e\x0aissues\x0ait\x0aitem\
s\x0aiterate\x0aits\x0ait\
self\x0ajob\x0ajoin\x0aJP\
EG\x0ajungle\x0ajust\x0aK\
araoke\x0akeep\x0akeep\
ing\x0akey\x0akind\x0akin\
g\x0aknown\x0alabel\x0ala\
bels\x0alandscape\x0al\
anguage\x0alarge\x0ala\
st\x0alater\x0alatest\x0a\
lawn\x0alayout\x0alead\
\x0aleader\x0aleaders\x0a\
lean\x0aleaves\x0aleav\
ing\x0aleft\x0alemma\x0al\
ength\x0aless\x0alet\x0al\
evel\x0alevels\x0alibr\
aries\x0alibrary\x0ali\
es\x0alike\x0alikely\x0al\
imit\x0alimiting\x0ali\
mits\x0aline\x0alinear\
\x0alines\x0alinewidth\
\x0alink\x0alinked\x0alin\
king\x0aLinux\x0alist\x0a\
lists\x0alittle\x0aliv\
es\x0aload\x0aloading\x0a\
loads\x0alocated\x0alo\
cation\x0alocations\
\x0alogo\x0along\x0alonge\
r\x0alook\x0alooked\x0alo\
oking\x0alooks\x0alook\
up\x0alookups\x0aloop\x0a\
lout\x0alow\x0amacro\x0am\
ade\x0amagazine\x0amag\
ic\x0amain\x0amajor\x0ama\
ke\x0amakes\x0amaking\x0a\
manage\x0amanaged\x0am\
anaging\x0amandator\
y\x0amanipulate\x0aman\
ipulation\x0amanner\
\x0amany\x0amap\x0amaps\x0aM\
arch\x0amargin\x0amask\
\x0amasking\x0aMassach\
usetts\x0amatch\x0amat\
hematical\x0amaximu\
m\x0amay\x0ameans\x0ameet\
\x0amember\x0amembers\x0a\
memory\x0amerged\x0ame\
thod\x0amight\x0amilli\
seconds\x0aminimize\
\x0aminimum\x0aminor\x0am\
ix\x0aMNG\x0amode\x0amode\
l\x0amodels\x0amodes\x0am\
odified\x0amodule\x0am\
oments\x0amonitored\
\x0amonthly\x0amore\x0amo\
st\x0amostly\x0amove\x0am\
uch\x0amultitude\x0aMu\
nich\x0amust\x0aname\x0an\
amed\x0anames\x0aneces\
sary\x0aneed\x0aneeded\
\x0aneeds\x0anetwork\x0an\
ew\x0anews\x0anewslett\
er\x0anext\x0anicely\x0an\
o\x0anone\x0anormally\x0a\
Norway\x0anot\x0anote\x0a\
notes\x0anothing\x0ano\
tifies\x0anotify\x0ano\
w\x0anull\x0anumber\x0anu\
mbered\x0anumbering\
\x0anumbers\x0aNydalen\
\x0aobject\x0aobjects\x0a\
obtain\x0aobtaining\
\x0aodd\x0aof\x0aoff\x0aoffi\
ce\x0aoffset\x0aoffset\
s\x0aoften\x0aold\x0aon\x0ao\
nce\x0aone\x0aones\x0aonl\
ine\x0aonly\x0aonto\x0aop\
acity\x0aopaque\x0aope\
n\x0aopens\x0aoperates\
\x0aoperating\x0aopera\
tion\x0aoperations\x0a\
operator\x0aopportu\
nity\x0aopposed\x0aopt\
imize\x0aoption\x0aopt\
ionally\x0aoptions\x0a\
or\x0aOR\x0aorder\x0aordi\
nary\x0aoriginal\x0aor\
iginally\x0aOslo\x0aot\
her\x0aotherwise\x0aou\
r\x0aout\x0aouter\x0aoutg\
oing\x0aoutput\x0aouts\
ide\x0aover\x0aovercom\
ing\x0aoverrides\x0aov\
erview\x0aown\x0aowner\
\x0aowners\x0apace\x0aPac\
ific\x0apackage\x0apac\
kages\x0apackets\x0apa\
ge\x0apages\x0apaint\x0ap\
ainted\x0apainting\x0a\
paragraph\x0aparagr\
aphs\x0aparameters\x0a\
parent\x0aParis\x0apar\
se\x0apart\x0apartial\x0a\
partially\x0apartic\
ular\x0apartners\x0apa\
rts\x0aparty\x0apassed\
\x0apassing\x0apatches\
\x0apath\x0apattern\x0apa\
tterns\x0apause\x0aPDF\
\x0apeek\x0apending\x0ape\
rform\x0aperformed\x0a\
performs\x0apermiss\
ion\x0apermutations\
\x0apersonal\x0apick\x0ap\
ie\x0apipe\x0apixel\x0api\
xels\x0aplace\x0aplace\
s\x0aplanning\x0aplatf\
orms\x0aplay\x0aplayer\
s\x0aplaying\x0aplease\
\x0apleasing\x0aplugin\
\x0aplugins\x0aplus\x0aPN\
G\x0apointer\x0apop\x0apo\
pular\x0apopulates\x0a\
porter\x0aPorter\x0apo\
rtrait\x0apossibili\
ty\x0apossible\x0apote\
ntial\x0apotentiall\
y\x0apower\x0apowers\x0ap\
receded\x0apresence\
\x0apresent\x0aprevent\
\x0aprevents\x0aprevio\
us\x0apreviously\x0apr\
imarily\x0aprimary\x0a\
primitives\x0aprint\
ed\x0aprinting\x0aprio\
r\x0aprobably\x0aprobl\
em\x0aprocess\x0aproce\
sses\x0aprocessing\x0a\
produce\x0aproduced\
\x0aproduces\x0aproduc\
ts\x0aprogramming\x0ap\
rograms\x0aproject\x0a\
projects\x0aproof\x0ap\
roper\x0aproperly\x0ap\
roperties\x0aproper\
ty\x0aproposed\x0aprop\
osition\x0apros\x0apro\
tocols\x0aproud\x0apro\
vide\x0aprovided\x0apr\
ovides\x0aprovision\
\x0aproxy\x0apublic\x0apu\
blished\x0apunch\x0apu\
nches\x0apursuing\x0ap\
ut\x0aQt\x0aQtopia\x0aqua\
lity\x0aquarter\x0aqua\
rterly\x0aqueried\x0aq\
ueries\x0aquery\x0aque\
stion\x0aquestions\x0a\
radial\x0aragged\x0ara\
nge\x0arate\x0arates\x0ar\
ather\x0aratio\x0araw\x0a\
read\x0areader\x0aread\
ing\x0areads\x0aready\x0a\
real\x0arealistic\x0ar\
eally\x0areceived\x0ar\
ecent\x0arecognized\
\x0arecommended\x0arec\
ompile\x0arectangle\
\x0arectangular\x0ared\
\x0aredistribute\x0are\
ducing\x0areference\
\x0areferences\x0arefl\
ect\x0aregardless\x0ar\
egional\x0aregister\
\x0aregistered\x0aregi\
stration\x0areimple\
ment\x0areimplement\
ation\x0areimplemen\
ted\x0arelease\x0arele\
ased\x0areleases\x0are\
liable\x0arely\x0arema\
ins\x0aremember\x0arem\
oved\x0aremoves\x0arep\
eatedly\x0areplace\x0a\
report\x0arepresent\
\x0arepresented\x0arep\
resents\x0areproduc\
ed\x0arequested\x0areq\
uire\x0arequired\x0are\
quires\x0aresetting\
\x0aresides\x0aresolve\
\x0arespective\x0aresp\
ectively\x0arespons\
e\x0arest\x0arestart\x0ar\
esult\x0aresulting\x0a\
resume\x0areturn\x0are\
turning\x0areturns\x0a\
reuse\x0arevealing\x0a\
rich\x0ariches\x0arigh\
t\x0aroadshow\x0arole\x0a\
Roman\x0arouter\x0arou\
ters\x0arule\x0arun\x0aru\
nner\x0arunners\x0arun\
ning\x0aruns\x0asake\x0as\
ales\x0asalespeople\
\x0asame\x0asample\x0aSan\
 Jose\x0asave\x0asaved\
\x0asaves\x0asay\x0ascala\
ble\x0ascale\x0ascanli\
ne\x0ascene\x0ascenes\x0a\
schedule\x0aschool\x0a\
script\x0aseam\x0aseam\
less\x0asearch\x0asear\
ches\x0asearching\x0as\
econd\x0aseconds\x0ase\
ction\x0asections\x0as\
ecurity\x0asee\x0aseen\
\x0aselection\x0asemin\
ar\x0aseminars\x0asend\
ing\x0aseparated\x0ase\
parates\x0aseries\x0as\
ervice\x0aservices\x0a\
set\x0asetting\x0asetu\
p\x0aseven\x0aseventh\x0a\
several\x0ashade\x0ash\
adow\x0ashape\x0ashare\
s\x0ashaves\x0ashine\x0as\
horter\x0ashould\x0ash\
ow\x0ashown\x0ashows\x0as\
ide\x0asignal\x0asigna\
ls\x0asignature\x0asig\
nificantly\x0asimil\
ar\x0asimilarily\x0asi\
milarly\x0asimple\x0as\
implest\x0asimplifi\
ed\x0asimplifying\x0as\
imply\x0asimulate\x0as\
imultaneous\x0asinc\
e\x0asingle\x0asize\x0asi\
zes\x0aslightly\x0aslo\
pe\x0aslot\x0aslowing\x0a\
small\x0asmaller\x0aso\
\x0asocket\x0asockets\x0a\
software\x0asolutio\
ns\x0asolved\x0asome\x0as\
oon\x0asort\x0asorting\
\x0asource\x0asources\x0a\
south\x0aspace\x0aspec\
ial\x0aspecialized\x0a\
specific\x0aspecifi\
cally\x0aspecificat\
ion\x0aspecificatio\
ns\x0aspecified\x0aspe\
cify\x0aspeed\x0aspend\
\x0asplit\x0aSQL\x0astand\
ard\x0astandards\x0ast\
art\x0astarts\x0astarv\
e\x0astate\x0astates\x0as\
tatic\x0asteady\x0aste\
aling\x0astep\x0astill\
\x0astop\x0astopwatch\x0a\
store\x0astored\x0asto\
res\x0astraightforw\
ard\x0astream\x0astrin\
g\x0astrings\x0astruct\
ure\x0astructured\x0as\
trut\x0astyle\x0astyle\
s\x0astyling\x0asubcla\
ss\x0asubclassing\x0as\
ubdirectory\x0asubs\
ection\x0asubsectio\
ns\x0asucceeds\x0asucc\
ess\x0asuccessful\x0as\
uccessfully\x0asuch\
\x0asuggestion\x0asugg\
estions\x0asuitable\
\x0asupport\x0asupport\
ed\x0asupports\x0asupp\
ose\x0asupposes\x0asur\
e\x0aswitch\x0aswitche\
s\x0asymbol\x0asymbols\
\x0asynonyms\x0asystem\
\x0asystems\x0atable\x0at\
ables\x0atags\x0atake\x0a\
takes\x0atap\x0atarget\
\x0atargets\x0aTCP\x0atea\
m\x0atechnique\x0atech\
nology\x0atemplate\x0a\
templates\x0aTexas\x0a\
text\x0athan\x0athat\x0at\
he\x0atheir\x0athem\x0ath\
en\x0atheorem\x0athere\
\x0athese\x0athey\x0athic\
kness\x0athin\x0athird\
\x0athis\x0athose\x0athre\
e\x0athrottling\x0athr\
ough\x0atightly\x0atim\
e\x0atimer\x0atimes\x0ati\
ny\x0atips\x0atitle\x0ati\
tles\x0ato\x0atogether\
\x0atoo\x0atop\x0atorrent\
\x0atotal\x0atour\x0atrad\
emarks\x0atraffic\x0at\
raining\x0atransact\
ion\x0atransfer\x0atra\
nsferred\x0atransfe\
rring\x0atransfers\x0a\
translucency\x0atra\
nslucent\x0atranspa\
rency\x0atransparen\
t\x0atravel\x0atravele\
d\x0atrue\x0atry\x0aturn\x0a\
twice\x0atwo\x0atype\x0at\
yped\x0atypical\x0atyp\
ically\x0aunable\x0aun\
der\x0aunderlying\x0au\
nderstanding\x0aund\
oes\x0aunique\x0aunite\
d\x0aunlike\x0aunpack\x0a\
unsigned\x0auntil\x0au\
ntouched\x0aup\x0aupda\
te\x0aupdated\x0aupdat\
es\x0aupload\x0aupload\
ing\x0auploads\x0aus\x0au\
se\x0aused\x0auseful\x0au\
ser\x0ausers\x0auses\x0au\
sing\x0ausual\x0ausual\
ly\x0avalid\x0avalue\x0av\
alues\x0avariable\x0av\
ariation\x0avariety\
\x0avarious\x0avector\x0a\
venturing\x0averify\
ing\x0aversa\x0aversio\
n\x0aversions\x0averti\
cal\x0avery\x0avia\x0avic\
e\x0avirtual\x0avisual\
\x0avoid\x0aVP\x0awaiting\
\x0aWales\x0awant\x0awant\
s\x0awas\x0away\x0aways\x0aw\
e\x0aweb\x0awebsite\x0awe\
ll\x0awere\x0awhat\x0awhe\
n\x0awhenever\x0awhere\
\x0awhether\x0awhich\x0aw\
hile\x0awhistle\x0awhi\
te\x0awho\x0awhole\x0awhy\
\x0awidget\x0awidgets\x0a\
width\x0awidths\x0awil\
l\x0awindow\x0awindows\
\x0awish\x0awith\x0awitho\
ut\x0aword\x0awords\x0awo\
rk\x0aworking\x0aworks\
\x0awould\x0awrap\x0awrap\
per\x0awrite\x0awrites\
\x0awriting\x0awriting\
s\x0awritten\x0aX\x0aX11\x0a\
XOR\x0ayear\x0ayears\x0ay\
es\x0ayou\x0ayour\x0azero\
\x0a\
"

qt_resource_name = b"\
\x00\x09\
\x0alxC\
\x00r\
\x00e\x00s\x00o\x00u\x00r\x00c\x00e\x00s\
\x00\x0c\
\x0fjM\x94\
\x00w\
\x00o\x00r\x00d\x00l\x00i\x00s\x00t\x00.\x00t\x00x\x00t\
"

qt_resource_struct = b"\
\x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\
\x00\x00\x00\x00\x00\x00\x00\x00\
\x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x02\
\x00\x00\x00\x00\x00\x00\x00\x00\
\x00\x00\x00\x18\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\
\x00\x00\x01\x8eh\xfbB\x15\
"

def qInitResources():
    QtCore.qRegisterResourceData(0x03, qt_resource_struct, qt_resource_name, qt_resource_data)

def qCleanupResources():
    QtCore.qUnregisterResourceData(0x03, qt_resource_struct, qt_resource_name, qt_resource_data)

qInitResources()
